# Generated by Django 5.0.6 on 2024-06-14 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('trailer_link', models.CharField(blank=True, max_length=3000, null=True)),
                ('source_link', models.CharField(blank=True, max_length=3000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
