# Generated by Django 5.0.6 on 2024-06-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tags_movies_vote_total_review_movies_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
